/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Game {
  'id' : bigint,
  'date' : Time,
  'opponentScore' : bigint,
  'home' : boolean,
  'ourScore' : bigint,
  'opponent' : string,
}
export interface Player {
  'id' : bigint,
  'name' : string,
  'number' : bigint,
  'position' : PositionType,
}
export type PositionType = { 'goalie' : null } |
  { 'midfield' : null } |
  { 'defense' : null } |
  { 'attack' : null };
export interface StatLine {
  'groundBalls' : bigint,
  'assists' : bigint,
  'turnovers' : bigint,
  'saves' : bigint,
  'shots' : bigint,
  'goals' : bigint,
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addGame' : ActorMethod<[Time, string, bigint, bigint, boolean], bigint>,
  'addPlayer' : ActorMethod<[string, bigint, PositionType], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllStats' : ActorMethod<[], Array<[bigint, StatLine]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGames' : ActorMethod<[], Array<Game>>,
  'getPlayerStats' : ActorMethod<[bigint], StatLine>,
  'getPlayers' : ActorMethod<[], Array<Player>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removePlayer' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updatePlayerStats' : ActorMethod<[bigint, StatLine], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];