/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const PositionType = IDL.Variant({
  'goalie' : IDL.Null,
  'midfield' : IDL.Null,
  'defense' : IDL.Null,
  'attack' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const StatLine = IDL.Record({
  'groundBalls' : IDL.Nat,
  'assists' : IDL.Nat,
  'turnovers' : IDL.Nat,
  'saves' : IDL.Nat,
  'shots' : IDL.Nat,
  'goals' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Game = IDL.Record({
  'id' : IDL.Nat,
  'date' : Time,
  'opponentScore' : IDL.Nat,
  'home' : IDL.Bool,
  'ourScore' : IDL.Nat,
  'opponent' : IDL.Text,
});
export const Player = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'number' : IDL.Nat,
  'position' : PositionType,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addGame' : IDL.Func(
      [Time, IDL.Text, IDL.Nat, IDL.Nat, IDL.Bool],
      [IDL.Nat],
      [],
    ),
  'addPlayer' : IDL.Func([IDL.Text, IDL.Nat, PositionType], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllStats' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, StatLine))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
  'getPlayerStats' : IDL.Func([IDL.Nat], [StatLine], ['query']),
  'getPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removePlayer' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updatePlayerStats' : IDL.Func([IDL.Nat, StatLine], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const PositionType = IDL.Variant({
    'goalie' : IDL.Null,
    'midfield' : IDL.Null,
    'defense' : IDL.Null,
    'attack' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const StatLine = IDL.Record({
    'groundBalls' : IDL.Nat,
    'assists' : IDL.Nat,
    'turnovers' : IDL.Nat,
    'saves' : IDL.Nat,
    'shots' : IDL.Nat,
    'goals' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Game = IDL.Record({
    'id' : IDL.Nat,
    'date' : Time,
    'opponentScore' : IDL.Nat,
    'home' : IDL.Bool,
    'ourScore' : IDL.Nat,
    'opponent' : IDL.Text,
  });
  const Player = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'number' : IDL.Nat,
    'position' : PositionType,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addGame' : IDL.Func(
        [Time, IDL.Text, IDL.Nat, IDL.Nat, IDL.Bool],
        [IDL.Nat],
        [],
      ),
    'addPlayer' : IDL.Func([IDL.Text, IDL.Nat, PositionType], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllStats' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, StatLine))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGames' : IDL.Func([], [IDL.Vec(Game)], ['query']),
    'getPlayerStats' : IDL.Func([IDL.Nat], [StatLine], ['query']),
    'getPlayers' : IDL.Func([], [IDL.Vec(Player)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removePlayer' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updatePlayerStats' : IDL.Func([IDL.Nat, StatLine], [], []),
  });
};

export const init = ({ IDL }) => { return []; };